version: '3'

services:
  api_web:
    build: ./apimanager
    command: bash -c "python ./apimanager/manage.py makemigrations && python ./apimanager/manage.py migrate && python ./apimanager/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always

  cli_web:
    build: ./cliCodec
    command: bash -c "python ./cliCodec/manage.py makemigrations && python ./cliCodec/manage.py migrate && python ./cliCodec/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always

  user_auth:
    build: ./user_auth_system
    command: bash -c "python ./user_auth_system/manage.py makemigrations && python ./user_auth_system/manage.py migrate && python ./user_auth_system/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always
    